### ISSUE TITLE
Add more side dishes with vegetables

### ISSUE THREAD

**Issue by crichID** [githubschool/pm-cookbook#26]
This cookbook is missing vegetable recipes. Let's add some with:
- [x] Carrots
- [x] Green Beans
- [ ] Artichoke

**Comment by githubteacher** [comment]
What other types of dishes would be good here?

cc @githubschool/vegetarians

**Comment by loranallensmith** [comment]
I'm not sure an artichoke is technically a vegetable.  

I mean, I know it is obviously not :poultry_leg:, but isn't it technically a type of seed?  :bow:

**Comment by githubteacher** [comment]
Let's ask the experts. Hey @githubschool/vegetarians what do you think?
